"""empty message

Revision ID: 421c60e7ad98
Revises: 8bf07d973a08
Create Date: 2020-04-18 02:52:10.752089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421c60e7ad98'
down_revision = '8bf07d973a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('phone', sa.String(length=250), nullable=False),
    sa.Column('state', sa.String(length=250), nullable=False),
    sa.Column('lga', sa.String(length=250), nullable=False),
    sa.Column('ward', sa.String(length=250), nullable=False),
    sa.Column('intervention_type', sa.String(length=250), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('education', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=250), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beneficiary')
    # ### end Alembic commands ###
